# This workflow is designed to run the Divine Pantheon code review process on pull requests.
# It uses the autogen-agentchat and autogen-core libraries to perform the review.
# The workflow is triggered on pull request events and can also be manually triggered.
name: Divine Pantheon Code Review

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number to review'
        required: true
permissions: write-all

jobs:
  divine-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai tiktoken PyGithub autogen-agentchat autogen-core autogen-ext[openai,azure]

      - name: Code Review
        uses: freeedcom/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4-1106-preview"
          exclude: "yarn.lock,dist/**"
      
      - name: Run Pantheon Review
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_PR_NUMBER: ${{ github.event.pull_request.number || github.event.inputs.pr_number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/pantheon_pr_reviewer.py
